on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: unfor19/install-aws-cli-action@v1

      # TODO - use your preferred method of obtaining your AWS Credentials here
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::xxx:role/xxx
          role-session-name: samplerolesession
          aws-region: AWS_REGION

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build
        working-directory: services/go/hello_world
        run: go build -o bootstrap -tags lambda.norpc -trimpath -buildvcs=false

      - uses: vimtor/action-zip@v1
        with:
          files: services/go/hello_world/bootstrap
          dest: services/go/hello_world/hello_world.zip

      - name: Compare Hashes & Upload
        working-directory: services/go/hello_world
        run: |
          GOLANG_BINARY_HASH=$(shasum bootstrap | cut -d' ' -f1)

          S3_METADATA=$(aws s3api head-object \
                    --bucket BUCKET_NAME \
                    --key go/hello_world.zip \
                    --query 'Metadata.sha256sum' \
                    2> /dev/null \
                    | tr -d '"')

          if [ "$GOLANG_BINARY_HASH" != "$S3_METADATA" ]; then
            echo "Hashes are not equal between local ($GOLANG_BINARY_HASH) and S3 ($S3_METADATA), or object doesn't exist on S3. Syncing code to S3"
            aws s3 cp hello_world.zip s3://BUCKET_NAME/go/hello_world.zip --metadata "sha256sum=$binary_hash"
          else
            echo "Hashes are equal. Not syncing to S3"
          fi
